import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "바버샵 💇‍♂️",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <body>{children}</body>;
}
